version: '3.8'
services:
  # Aquí se añadirán los servicios (backend, frontend, db, etc.)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
volumes:
  mongodb_data: