name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8 # Usar la versión 8 de pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Usar la versión de Node.js que se ajuste al proyecto
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - name: List files in root
        run: ls -la
      - name: List files in node_modules/.bin
        run: ls -la node_modules/.bin
      - name: Run lint
        run: npx eslint
      - name: Run type check
        run: pnpm tsc --noEmit
      - name: Run tests
        run: pnpm test
